name: deploy

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18.15'
          cache: 'yarn'
      - name: Install root dependencies
        run: yarn install --immutable
      - name: Install wallets dependencies
        run:
          cd ./wallets-testing
          yarn install --immutable
          cd ..
      - name: Run lint
        run: yarn lint

      - name: Setup NPM token
        run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish to NPM
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          git config --global user.email "ci@github.com"
          git config --global user.name "Robot"
          yarn release
